import logging
from algokit_utils import Algorithm, Deployer
from algosdk.v2client.algod import AlgodClient
from algosdk.v2client.indexer import IndexerClient
from algosdk import account

# Import the NEW client generated by your build
from smart_contracts.artifacts.hello_world.hello_world_client import HelloWorldClient

logger = logging.getLogger(__name__)

def deploy(
    algod_client: AlgodClient,
    indexer_client: IndexerClient,
    app_spec: str,
    deployer: Deployer,
) -> None:
    
    # 1. Generate Fake Accounts for Seller & Arbiter
    # (Because your Escrow needs these 2 addresses to be created)
    _, seller_addr = account.generate_account()
    _, arbiter_addr = account.generate_account()
    
    logger.info(f"Test Seller: {seller_addr}")
    logger.info(f"Test Arbiter: {arbiter_addr}")

    # 2. Initialize the App Client
    app_client = HelloWorldClient(
        algod_client=algod_client,
        creator=deployer.sender,
        indexer_client=indexer_client,
    )

    # 3. Deploy the App
    # We pass the 2 addresses as arguments to the 'create' function
    deploy_response = app_client.deploy(
        on_schema_break=Algorithm.Replace,
        on_update=Algorithm.Update,
        create_args=(seller_addr, arbiter_addr) 
    )

    logger.info(f"✅ Deployed App ID: {deploy_response.app.app_id}")